import weaviate
import os
from dotenv import load_dotenv

load_dotenv()

# --- Configuration ---
WEAVIATE_URL = os.getenv("WEAVIATE_URL", "http://localhost:8080")
CLASS_NAME = "FortifAIMasterMemory" 
VECTOR_DIMENSION = 768
DISTANCE = "cosine"

def get_weaviate_client() -> weaviate.Client:
    """Initializes and returns the Weaviate client."""
    client = weaviate.Client(
        url=WEAVIATE_URL,
        # Add API key/authentication if using Weaviate Cloud/Auth
        # auth_client_secret=weaviate.AuthApiKey(api_key="YOUR_API_KEY")
    )
    return client

def ensure_schema_exists(client: weaviate.Client) -> None:
    """
    Ensures the Weaviate class (collection) exists with the correct properties
    for personalized RAG and safety filtering.
    """
    if client.schema.exists(CLASS_NAME):
        print(f"Schema for '{CLASS_NAME}' already exists. Skipping creation.")
        return

    print(f"Creating schema for '{CLASS_NAME}'...")

    class_obj = {
        "class": CLASS_NAME,
        "description": "Master memory store for personalized RAG, replacing Qdrant.",
        # Embeddings are pre-generated by GoogleGenerativeAIEmbeddings in the ingestion script
        "vectorizer": "none", 
        "vectorizerConfig": {
            "skip": True,
            "vectorIndexConfig": {
                "vectorCacheMaxObjects": 100000000000,
                "distance": DISTANCE,
                "dimensions": VECTOR_DIMENSION
            }
        },
        "properties": [
            {
                "name": "content", 
                "dataType": ["text"],
                "description": "The chunk of text from the source document.",
            },
            {
                "name": "patient_id", 
                "dataType": ["text"],
                "description": "The unique ID of the patient who owns this memory.",
                "moduleConfig": {
                    "text2vec-contextionary": {"skip": True} 
                }
            },
            {
                "name": "is_sensitive", # for safety filtering 
                "dataType": ["boolean"],
                "description": "Flag to mark content as sensitive (e.g., related to trauma/death).",
                "moduleConfig": {
                    "text2vec-contextionary": {"skip": True} 
                }
            },
            # Including other metadata fields from old Qdrant payload:
            {"name": "source_filename", "dataType": ["text"]},
            {"name": "topic", "dataType": ["text"]},
            # Note: Weaviate expects multi-value strings as "text[]"
            {"name": "entities", "dataType": ["text[]"]}, 
            {"name": "chunk_index", "dataType": ["int"]},
            {"name": "total_chunks", "dataType": ["int"]},
            {"name": "ingested_at", "dataType": ["date"]},
        ]
    }

    try:
        client.schema.create_class(class_obj)
        print(f"Schema '{CLASS_NAME}' created successfully.")
    except Exception as e:
        print(f"Error creating schema: {e}")
        raise